scheme: Pisces

sidebar:
  position: right

# **添加评论系统**
#
# 步骤：
# 1. 在 GitHub 中创建一个 OAuth 应用；
# 2. 填充以下配置。
gitalk:
  enable: true
  github_id: yetrun # GitHub repo owner
  repo:  yetrun.github.io # Repository name to store issues
  client_id: a386f9dc0f5fe109f2d1 # GitHub Application Client ID
  client_secret: e2a830c7febee5b141b227032f95161f738be604 # GitHub Application Client Secret
  admin_user: yetrun # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN
